### PR TITLE
Reduce oid binary size

### PR DESCRIPTION
**Pull request by TeroJaasko**
Add bunch of ifdefs to help ARMC5's linker to remove unused code from oid.c. On our L0/L4 devices, this reduces the size of oid.o from 1153 to 468 bytes.

## Status
**READY**

## Requires Backporting

NO  

## Migrations
If there is any API change, what's the incentive and logic for it.

NO

## Additional comments
Any additional information that could be of interest

## Todos
- [ ] Tests
- [ ] Documentation
- [ ] Changelog updated
- [ ] Backported

## Steps to test or reproduce
Outline the steps to test or reproduce the PR here.

Build size changes can be observed on Mbed OS uARM builds with feedback files.

### CODE REVIEW

**Comment by TeroJaasko** [comment]
Eh, let's see if CI finds more build configuration permutations which fail. Originally I tested just with "make check" but failed to notice the all.sh. I have been running ```tests/scripts/all.sh --seed 4 --keep-going test_*``` locally for quite a many hours now with latest version and so far no new build failures.

**Review by shelib01 — APPROVED** [review]

**Comment by shelib01** [comment]
@AndrzejKurek , please look on this PR and let me know if you have any concerns

**Review by AndrzejKurek — APPROVED** [review]

**Comment by AndrzejKurek** [comment]
It would be best to add a test configuration to all.sh which tests default config + remove info, but that can be done later, or separately.
Edit: or add it to the baremetal config, so it's tested there.

**Comment by AndrzejKurek** [comment]
Just noticed that `MBEDTLS_X509_REMOVE_INFO` is in baremetal config already :) LGTM.

**Pull request merged**
